version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://aakshkr:*Aakash94707#@cluster0.xxxxx.mongodb.net/ecommerce?retryWrites=true&w=majority
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
