name: CI/CD pipeline

on: 
   push:
     branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest -f server/Dockerfile .

      - name: Build Frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest -f client/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.region }}

      - name: Set up kubectl
        run : VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt) && \
               curl -LO "https://dl.k8s.io/release/${VERSION}/bin/darwin/amd64/kubectl" && \
               chmod +x ./kubectl && \
               sudo mv ./kubectl /usr/local/bin/kubectl && \
            

             

        
          
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.region }} --name mern-app

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/mern-backend mern-backend=${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          kubectl set image deployment/mern-frontend mern-frontend=${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          kubectl rollout status deployment/mern-backend
          kubectl rollout status deployment/mern-frontend
          

