name: CI/CD pipeline

on: 
   push:
     branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build Backend and Frontend Docker Images
      - name: Build Docker images
        run: docker-compose build

      # Test Backend
      - name: Test Backend
        run: docker-compose run backend npm test

      # Test Frontend
      - name: Test Frontend
        run: docker-compose run frontend npm test


       
